Applying concepts in a Newsweek clone page
kenderb/Using-bootstrap pull request #2
Opened 2020-10-14 17:08 UTC by kenderb

The page contains the next mains tags:

- A header tag that contains the navbar with some buttons.
- Combination of the Grid system and bootstrap classes.
- Contain media Query for 2 breakpoints.
- A footer that contains some lists and images.

2020-10-14 17:49 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello team!
Very good job in this project! 👍 
Linters are green 🟢 
You set up bootstrap correctly 👏 
Professional readme and descriptive commit messages 💯 
I am impressed! 🥇 

However, we still need to implement some changes to get this project approved 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review
Good luck 😺 

## Mandatory Changes
- Kindly, modify font size and spacing in all the project, make it equal to the original
- In the editors pick section the topic is missing, kindly add it
![Capture1](https://user-images.githubusercontent.com/56809963/96025731-d6948a00-0e55-11eb-8c56-77e1459a0e77.PNG)
![Capture](https://user-images.githubusercontent.com/56809963/96025736-d85e4d80-0e55-11eb-9e03-65e0d16596d9.PNG)
- Screens below 990px:
   -  kindly fix the size of the columns in the US, business, sports... sections, it is not corresponding with the original
![Capture3](https://user-images.githubusercontent.com/56809963/96025817-f88e0c80-0e55-11eb-9041-7dd03413fad9.PNG)
![Capture2](https://user-images.githubusercontent.com/56809963/96025824-fa57d000-0e55-11eb-8162-a6c265a9a85f.PNG)

2020-10-14 17:49 UTC, javitocor commented on styles/main.css
> +    margin-bottom: 1rem;
Apply bootstrap classes wherever you can, please add bootstrap classes and reduce your CSS file.

2020-10-14 22:11 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__This is an excellent piece of work. It is so obvious that a lot of efforts have been put into the development of this project.  I can not approve it yet because there are some changes that are required, but overall, your project is looking good. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] Ensure that the height of the `SUBSCRIBE` section is the same as that of the `NEWSLETTER` section. This is in line with what we have on the original page.
- You should also adjust the width of the `SUBSCRIBE` section so that it's reduced to look like what we have on the original page.
Original page:
![22-54-26](https://user-images.githubusercontent.com/26856491/96049757-63e4d800-0e70-11eb-81f8-498b0c015080.png)

Your Clone page:
![22-55-34](https://user-images.githubusercontent.com/26856491/96049783-6c3d1300-0e70-11eb-9243-d4ba1edee251.png)

- [ ] The `US, WORLD, BUSINESS, TECH & SCIENCE, CULTURE, AND SPORTS` section are not displayed in small screen sizes (<768px) as seen in the original. Kindly hide them for this specific screen size.

**[ OPTIONAL CHANGES ]**
- As the main point of this project is to use Bootstrap, CSS rules like padding, margin, width, etc all have dedicated class names in bootstrap. You are advised to use Bootstrap classes for these features.


**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-15 01:53 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ]  Please add these folders into a single folder. This will help you to present your project professionally. 
![chrome-capture (68)](https://user-images.githubusercontent.com/58504655/96067283-cfe83000-0eb2-11eb-80b3-a15cd5845fb9.jpg)

- [ ] Please add image into its respective folder
![chrome-capture (69)](https://user-images.githubusercontent.com/58504655/96067322-f1e1b280-0eb2-11eb-9ec2-341b6ee4ece8.jpg)

- [ ]  Bootstrap projects make sure to less use the styles.css file for styles that could be done using Bootstrap classes since that's the main goal of the exercise. Things like font-weight, flex justifications, display, etc could be implemented completely with Bootstrap classes. [Please refer to the main page of bootstrap to learn more about bootstrap. ](https://getbootstrap.com/docs/4.5/getting-started/introduction/)
I have given a few suggestions below. Please have a look at the entire CSS file and change all the extra styling to bootstrap. In case you cannot implement a change, please leave that in the CSS file.  

- [ ] **This is incredible that you have a sticky navbar in your project which is not an easy task to do and most students could not achieve it. But on the original page, on scrolling, the navbar decreases its width, the date, location, and temperate disappears and the Newsweek logo takes their place.**   

**Clone**

![chrome-capture (57)](https://user-images.githubusercontent.com/58504655/96062210-90b7e000-0eae-11eb-92be-27c115e7228e.jpg)

**Original**

![chrome-capture (58)](https://user-images.githubusercontent.com/58504655/96062324-d8d70280-0eae-11eb-973c-0d18b9b93a49.jpg)

- [ ]  **`FEATURED STORIES, TOP STORY, THE DEBATE` should be aligned in the same row(In case of Tablet Mode only . Please make this correct.** 

**Clone** 

![chrome-capture (60)](https://user-images.githubusercontent.com/58504655/96062403-0a4fce00-0eaf-11eb-80f0-2e574e768a99.jpg)

**Original**

![chrome-capture (61)](https://user-images.githubusercontent.com/58504655/96062434-19368080-0eaf-11eb-8912-8d8a6be98084.jpg)

- [ ] **There is no white space on the original page before the ` IN THE MAGAZINE` section. Please have a look at the original page and work on it.** 

**Clone**

![chrome-capture (63)](https://user-images.githubusercontent.com/58504655/96062622-95c95f00-0eaf-11eb-9b44-52ae550f2487.jpg)

**Original**

![chrome-capture (62)](https://user-images.githubusercontent.com/58504655/96062678-b5f91e00-0eaf-11eb-80c8-551c914d6a61.jpg)

- [ ] In the footer please make your logo a link. 

- [ ] On the medium and small screen in the Newsletter section Free Signup button is overlapping the text. Please resolve this.

**Clone**

![chrome-capture (64)](https://user-images.githubusercontent.com/58504655/96065181-bb576800-0eb1-11eb-8b4c-f3320c7eb868.jpg)

**Original**

![chrome-capture (65)](https://user-images.githubusercontent.com/58504655/96065571-d5914600-0eb1-11eb-95f8-b3c060756378.jpg)

- [ ] On the small and medium screen original page in the **Subscribe** section, the text has more height than the clone. Please have a look below.

**Original** 

![chrome-capture (66)](https://user-images.githubusercontent.com/58504655/96066901-3882dd00-0eb2-11eb-9d3c-d32d7e6bcda1.jpg)

**Clone**

![chrome-capture (67)](https://user-images.githubusercontent.com/58504655/96067052-4df80700-0eb2-11eb-8cb3-a381d3a5aa66.jpg)


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-15 01:53 UTC, arslanbisharat commented on styles/main.css
> +  width: 8rem;
Please try to use bootstrap for this project. If a goal can be achieved from bootstrap, don't use CSS.

2020-10-15 01:53 UTC, arslanbisharat commented on styles/main.css
> +  font-size: 0.7rem;
Please try to use bootstrap for this project. If a goal can be achieved from bootstrap, don't use CSS.

2020-10-15 01:53 UTC, arslanbisharat commented on styles/main.css
> +  display: inline;
Please try to use bootstrap for this project. If a goal can be achieved from bootstrap, don't use CSS.

2020-10-15 01:53 UTC, arslanbisharat commented on styles/main.css
> +  width: 85%;
Please try to use bootstrap for this project. If a goal can be achieved from bootstrap, don't use CSS.

2020-10-15 01:53 UTC, arslanbisharat commented on styles/main.css
> +  font-size: 98%;
Please try to use bootstrap for this project. If a goal can be achieved from bootstrap, don't use CSS.

2020-10-15 01:53 UTC, arslanbisharat commented on styles/main.css
> +  font-size: medium;
Please try to use bootstrap for this project. If a goal can be achieved from bootstrap, don't use CSS.

2020-10-15 01:53 UTC, arslanbisharat commented on styles/main.css
> +  font-size: 1.3rem;
Please try to use bootstrap for this project. If a goal can be achieved from bootstrap, don't use CSS.

2020-10-15 01:53 UTC, arslanbisharat commented on styles/main.css
> +  font-size: small;
Please try to use bootstrap for this project. If a goal can be achieved from bootstrap, don't use CSS.

2020-10-15 01:53 UTC, arslanbisharat commented on styles/main.css
> +  font-size: 1rem;
Please try to use bootstrap for this project. If a goal can be achieved from bootstrap, don't use CSS.

2020-10-15 07:25 UTC, arslanbisharat requested changes
### Request changes 😳
I am very happy to see this project and I can see you worked hard on this project but I am sorry to inform you that I cannot approve this project because it is not completed yet. You need to work more on it. 
_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_
**Please have a look at the suggestions to get more understanding.**

- [ ] Bootstrap projects make sure to less use the styles.css file for styles that could be done using Bootstrap classes since that's the main goal of the exercise. Things like font-weight, flex justifications, display, etc could be implemented completely with Bootstrap classes. Please refer to the main page of bootstrap to learn more about bootstrap.
I have given a few suggestions below. Please have a look at the entire CSS file and change all the extra styling to bootstrap. In case you cannot implement a change, please leave that in the CSS file.

                                                        ### Large Screen

- [ ] Newsletter and subscribe section has not met the minimum requirement to approve this project. Please work on it. 

**Clone**

![chrome-capture (70)](https://user-images.githubusercontent.com/58504655/96087976-2b7be300-0ede-11eb-8999-ef87e1feacdd.jpg)

**Original**

![chrome-capture (71)](https://user-images.githubusercontent.com/58504655/96088000-35054b00-0ede-11eb-9c2a-cbf067460f62.jpg)

- [ ] Newsweek logo and social icons are not correctly aligned. And the space between the line and this section is way to more. 

**Clone**

![chrome-capture (72)](https://user-images.githubusercontent.com/58504655/96088182-7bf34080-0ede-11eb-80b7-88c54a37342d.jpg)


**Original**

![chrome-capture (73)](https://user-images.githubusercontent.com/58504655/96088291-a34a0d80-0ede-11eb-8420-57572d16ffd1.jpg)

                       ### Medium Size

- [x] On tablet mode text is overflowing in some sections. 

**Clone**

![chrome-capture (74)](https://user-images.githubusercontent.com/58504655/96088554-08056800-0edf-11eb-8e8d-c40c7764f3e7.jpg)

**Original**

![chrome-capture (75)](https://user-images.githubusercontent.com/58504655/96088643-2bc8ae00-0edf-11eb-8b1c-20a38313e80b.jpg)

- [x] Position of the DISSENT section is not correct as present on the original page. 

**Clone**

![chrome-capture (76)](https://user-images.githubusercontent.com/58504655/96088807-67fc0e80-0edf-11eb-93ce-d1a9c05e8e7f.jpg)

**Original**

![chrome-capture (77)](https://user-images.githubusercontent.com/58504655/96088999-a5609c00-0edf-11eb-9910-f8875ca0507a.jpg)


- [ ] In the subscribe section, the text and button are not present in their actual positions. I have given suggestions below. 

**Clone**

![chrome-capture (78)](https://user-images.githubusercontent.com/58504655/96089162-dccf4880-0edf-11eb-88a4-795501b78a7a.jpg)

**Original**

![chrome-capture (79)](https://user-images.githubusercontent.com/58504655/96089215-f2447280-0edf-11eb-8318-e3ffafcb53f0.jpg)

- [ ] Subscribe section and newsletter section should have the same width. 

**Clone**

![chrome-capture (80)](https://user-images.githubusercontent.com/58504655/96089405-39cafe80-0ee0-11eb-95ec-31e8a9fc6923.jpg)

**Original**

![chrome-capture (81)](https://user-images.githubusercontent.com/58504655/96089431-45b6c080-0ee0-11eb-8241-356a94f5a9b3.jpg)

                                      ### Small Screen

- [x] You have two breakpoints after opinion section. Please work on it as on the original page there is only one. 

**Clone**

![chrome-capture (84)](https://user-images.githubusercontent.com/58504655/96090017-12286600-0ee1-11eb-86da-5dd4d3e5dfbc.jpg)

**Original**

![chrome-capture (85)](https://user-images.githubusercontent.com/58504655/96090113-31bf8e80-0ee1-11eb-8b16-ceea104631d0.jpg)


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-10-15 17:51 UTC, kevincappuccino approved these changes
# [STATUS] PROJECT APPROVED 🍾 (⚠)

### I really like your project! Congrats team, you guys did an excellent job, you have my approval to go ahead and merge this pull request!

_**Clean and modular code, following the best practices, and the design looks great, keep it up!**_ 🥇

[OPTIONAL CHANGES]

**⚠These are mandatory changes, but since It wasn't pointed out earlier, I'll mark them as [OPTIONAL]:**
- [ ] Your navbar should be fixed in large screens;


## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-10-15 17:53 UTC, merged